// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVJwkKimQriifX9Hbo04iee3iCP5ZOgNk',
    appId: '1:389190447372:web:bc0c1d937d881c46c59929',
    messagingSenderId: '389190447372',
    projectId: 'ai-business-suite-3155e',
    authDomain: 'ai-business-suite-3155e.firebaseapp.com',
    storageBucket: 'ai-business-suite-3155e.firebasestorage.app',
    measurementId: 'G-4L7CLPLX3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT0G6AeUkWCoqG9HTN0PEJfzgwyQgSI_Y',
    appId: '1:389190447372:android:0baddb5f837aea62c59929',
    messagingSenderId: '389190447372',
    projectId: 'ai-business-suite-3155e',
    storageBucket: 'ai-business-suite-3155e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC15E85T5Jwcsqt1Ls0rHZzXkr9KrRuiQE',
    appId: '1:389190447372:ios:3e16a4c5b77fb45cc59929',
    messagingSenderId: '389190447372',
    projectId: 'ai-business-suite-3155e',
    storageBucket: 'ai-business-suite-3155e.firebasestorage.app',
    iosBundleId: 'com.dhinadts.aibusinesssuite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC15E85T5Jwcsqt1Ls0rHZzXkr9KrRuiQE',
    appId: '1:389190447372:ios:3e16a4c5b77fb45cc59929',
    messagingSenderId: '389190447372',
    projectId: 'ai-business-suite-3155e',
    storageBucket: 'ai-business-suite-3155e.firebasestorage.app',
    iosBundleId: 'com.dhinadts.aibusinesssuite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVJwkKimQriifX9Hbo04iee3iCP5ZOgNk',
    appId: '1:389190447372:web:2dbc66c7513c35b0c59929',
    messagingSenderId: '389190447372',
    projectId: 'ai-business-suite-3155e',
    authDomain: 'ai-business-suite-3155e.firebaseapp.com',
    storageBucket: 'ai-business-suite-3155e.firebasestorage.app',
    measurementId: 'G-1SK0CSTBGP',
  );
}
